//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillEnum
    {
        public SkillEnum()
        {
            this.Skills = new HashSet<Skill>();
        }
    
        public string Name { get; set; }
        public int OrderIndex { get; set; }
    
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
